# Copyright (c) 2025 Enes Korkmaz, Jascha Sonntag and David Koch

# This file is part of tourney-db-variants.

# tourney-db-variants is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# any later version.

# tourney-db-variants is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with tourney-db-variants. If not, see <http://www.gnu.org/licenses/>.

services:
  app:
    build: .
    volumes:
      - "./:/app"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s