# Copyright (c) 2025 Enes Korkmaz, Jascha Sonntag and David Koch

# This file is part of tourney-db-variants.

# tourney-db-variants is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# any later version.

# tourney-db-variants is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with tourney-db-variants. If not, see <http://www.gnu.org/licenses/>.

services:
  app:
    build: .
    volumes:
      - ./:/app
    depends_on:
      neo:
        condition: service_healthy

  neo:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/hello_neo
    volumes:
      - "./data:/data"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://0.0.0.0:7474"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 3s